timestamp = 2023-06-08T18:20:50Z
github = { repo = "input-output-hk/cardano-ledger", rev = "eae43793dc80533fe7f3fc02b76303e7df7d001f" }
subdir = 'eras/shelley/impl'

[[revisions]]
number = 1
timestamp = 2024-02-15T15:59:55Z
