timestamp = 2024-08-28T06:44:16Z
github = { repo = "input-output-hk/typed-protocols", rev = "67a9d95bb57f03d707647ae2c722054d1ea11f5f" }
subdir = 'typed-protocols'

[[revisions]]
number = 1
timestamp = 2024-08-28T17:27:21Z

[[revisions]]
number = 2
timestamp = 2024-09-20T09:00:00Z
