timestamp = 2024-06-07T12:46:28Z
github = { repo = "input-output-hk/marlowe-cardano", rev = "c86a8b5edcab7a19e3f2327e372b5919c93444b7" }
subdir = 'marlowe-contracts'

[[revisions]]
number = 1
timestamp = 2024-06-07T14:15:27Z
