timestamp = 2023-06-20T08:51:26Z
github = { repo = "input-output-hk/cardano-ledger", rev = "566853a6dbf6171919e058b92ac11dc36aa1a901" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2024-01-25T14:10:44Z
