timestamp = 2024-09-02T23:44:58Z
github = { repo = "IntersectMBO/ouroboros-consensus", rev = "3da919ffc0ef0105bc51f6bbd8dd12e8dd6990c6" }
subdir = 'ouroboros-consensus'

[[revisions]]
number = 1
timestamp = 2024-09-02T23:56:39Z
