timestamp = 2023-12-13T17:21:15Z
github = { repo = "input-output-hk/marlowe-cardano", rev = "db25114ec91ccdab3228b99e791fd7232f8625bf" }
subdir = 'marlowe-chain-sync'

[[revisions]]
number = 1
timestamp = 2023-12-13T19:05:30Z
