timestamp = 2022-10-17T00:00:00Z
github = { repo = "input-output-hk/cardano-base", rev = "0f3a867493059e650cda69e20a5cbf1ace289a57" }
subdir = 'cardano-crypto-praos'

[[revisions]]
number = 1
timestamp = 2025-01-29T20:54:25Z
