timestamp = 2023-07-20T22:17:39Z
github = { repo = "input-output-hk/cardano-ledger", rev = "fb85fbeedffe60258612e39cd786ce1cdc87fc9c" }
subdir = 'eras/shelley/impl'

[[revisions]]
number = 1
timestamp = 2024-02-15T15:59:55Z
