timestamp = 2024-06-18T12:42:43Z
github = { repo = "input-output-hk/cardano-ledger", rev = "923e75bf3e16da01f26ed1ab53d9aac7184fc699" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2024-08-08T07:17:26Z

[[revisions]]
number = 2
timestamp = 2024-12-11T19:55:09Z
