timestamp = 2022-10-17T00:00:00Z
github = { repo = "input-output-hk/cardano-base", rev = "4ef911eb7a4d628c938312ff4c92e7c0bb8c83a1" }
subdir = 'cardano-crypto-class'

[[revisions]]
number = 1
timestamp = 2023-03-15T16:30:48Z
