timestamp = 2023-04-05T21:13:03Z
github = { repo = "input-output-hk/cardano-ledger", rev = "f10f06f6ab96b5ee52a28ccc45b41a592efde4b7" }
subdir = 'eras/shelley/impl'

[[revisions]]
number = 1
timestamp = 2023-05-11T21:34:38Z

[[revisions]]
number = 2
timestamp = 2024-02-15T15:59:55Z
