timestamp = 2024-09-02T23:06:20Z
github = { repo = "IntersectMBO/ouroboros-consensus", rev = "3da919ffc0ef0105bc51f6bbd8dd12e8dd6990c6" }
subdir = 'strict-sop-core'

[[revisions]]
number = 1
timestamp = 2025-03-03T00:40:42Z
