timestamp = 2024-08-25T15:05:06Z
github = { repo = "IntersectMBO/cardano-ledger", rev = "d82ac6915424df5e151d5fa12ff6346ce814e7c3" }
subdir = 'eras/byron/crypto'

[[revisions]]
number = 1
timestamp = 2026-07-29T17:12:40Z
