timestamp = 2024-10-11T13:55:02Z
github = { repo = "intersectmbo/ouroboros-network", rev = "df3431f95ef9e47a8a26fd3376efd61ed0837747" }
subdir = 'cardano-client'

[[revisions]]
number = 1
timestamp = 2025-03-18T01:50:17Z
