timestamp = 2022-10-17T00:00:00Z
github = { repo = "input-output-hk/cardano-ledger", rev = "c7c63dabdb215ebdaed8b63274965966f2bf408f" }
subdir = 'libs/set-algebra'

[[revisions]]
number = 1
timestamp = 2023-04-28T10:23:01Z
