timestamp = 2023-05-11T21:41:19Z
github = { repo = "input-output-hk/cardano-ledger", rev = "6db84a7b77e19af58feb2f45dfc50aa70435967b" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2024-12-11T19:54:35Z

[[revisions]]
number = 2
timestamp = 2025-09-10T20:25:46Z
