timestamp = 2022-10-17T00:00:00Z
github = { repo = "input-output-hk/cardano-ledger", rev = "c7c63dabdb215ebdaed8b63274965966f2bf408f" }
subdir = 'eras/byron/ledger/impl'

[[revisions]]
number = 1
timestamp = 2023-03-21T14:31:41Z

[[revisions]]
number = 2
timestamp = 2023-03-21T14:33:41Z
