timestamp = 2025-02-10T13:27:27Z
github = { repo = "IntersectMBO/ouroboros-consensus", rev = "f0ec4d72bcb6a53ba7160ba602d1a2f488cb0dcf" }
subdir = 'ouroboros-consensus-cardano'

[[revisions]]
number = 1
timestamp = 2025-03-03T00:53:23Z
