timestamp = 2024-05-07T20:33:59Z
github = { repo = "intersectmbo/ouroboros-network", rev = "c5314093f33c01f910be59b24f092be8ceeff9b1" }
subdir = 'ouroboros-network'

[[revisions]]
number = 1
timestamp = 2024-05-29T10:15:00Z
