timestamp = 2025-01-28T11:15:21Z
github = { repo = "IntersectMBO/cardano-api", rev = "41ece2bc0fee984d50994e21ef8a30213a0abd7f" }
subdir = 'cardano-api'

[[revisions]]
number = 1
timestamp = 2025-02-11T21:18:23Z
