timestamp = 2026-03-07T07:44:25Z
github = { repo = "intersectmbo/ouroboros-network", rev = "17525c337a6209011fabd6916fa757efd44df6f8" }
subdir = 'cardano-diffusion'

[[revisions]]
number = 1
timestamp = 2026-03-13T16:01:53Z

[[revisions]]
number = 2
timestamp = 2026-03-20T13:09:44Z
