#!/usr/bin/env bash
set -euo pipefail

PACKAGES=(
    "Win32-network"
    "acts-generic"
    "aeson-record"
    "async-components"
    "base-deriving-via"
    "base16-aeson"
    "byron-spec-chain"
    "byron-spec-ledger"
    "cardano-api"
    "cardano-api-gen"
    "cardano-base"
    "cardano-binary"
    "cardano-binary-test"
    "cardano-cli"
    "cardano-client"
    "cardano-client-demo"
    "cardano-crypto-class"
    "cardano-crypto-peras"
    "cardano-crypto-praos"
    "cardano-crypto-test"
    "cardano-crypto-tests"
    "cardano-crypto-wrapper"
    "cardano-data"
    "cardano-diffusion"
    "cardano-git-rev"
    "cardano-ledger-allegra"
    "cardano-ledger-alonzo"
    "cardano-ledger-alonzo-test"
    "cardano-ledger-api"
    "cardano-ledger-babbage"
    "cardano-ledger-babbage-test"
    "cardano-ledger-binary"
    "cardano-ledger-byron"
    "cardano-ledger-byron-test"
    "cardano-ledger-conway"
    "cardano-ledger-conway-test"
    "cardano-ledger-core"
    "cardano-ledger-dijkstra"
    "cardano-ledger-mary"
    "cardano-ledger-pretty"
    "cardano-ledger-shelley"
    "cardano-ledger-shelley-ma"
    "cardano-ledger-shelley-ma-test"
    "cardano-ledger-shelley-test"
    "cardano-ledger-test"
    "cardano-lmdb"
    "cardano-lmdb-simple"
    "cardano-node"
    "cardano-node-capi"
    "cardano-node-chairman"
    "cardano-node-emulator"
    "cardano-node-socket-emulator"
    "cardano-ping"
    "cardano-prelude"
    "cardano-prelude-test"
    "cardano-prometheus-tracker"
    "cardano-protocol-tpraos"
    "cardano-recon-framework"
    "cardano-rpc"
    "cardano-slotting"
    "cardano-strict-containers"
    "cardano-submit-api"
    "cardano-testnet"
    "cardano-timeseries-io"
    "cardano-topology"
    "cardano-tracer"
    "cardano-wallet-read"
    "cooked-validators"
    "decentralized-message-queue"
    "diff-containers"
    "dmq-node"
    "ekg-forward"
    "eventuo11y-extras"
    "fingertree-rm"
    "freer-extras"
    "goblins"
    "haskell-accumulator"
    "hasql-dynamic-syntax"
    "heapwords"
    "hydra-cardano-api"
    "hydra-chain-observer"
    "hydra-invoices"
    "hydra-node"
    "hydra-plutus"
    "hydra-plutus-extras"
    "hydra-prelude"
    "hydra-test-utils"
    "hydra-tui"
    "iog-contra-tracer"
    "iohk-monitoring"
    "kes-agent"
    "kes-agent-crypto"
    "ledger-state"
    "lobemo-backend-aggregation"
    "lobemo-backend-ekg"
    "lobemo-backend-monitoring"
    "lobemo-backend-trace-forwarder"
    "lobemo-scribe-systemd"
    "locli"
    "marlowe"
    "marlowe-cardano"
    "marlowe-chain-sync"
    "marlowe-client"
    "marlowe-object"
    "marlowe-plutus"
    "marlowe-protocols"
    "marlowe-runtime"
    "marlowe-runtime-web"
    "marlowe-spec-test"
    "marlowe-test"
    "measures"
    "mempack-scls"
    "merkle-tree-incremental"
    "monoidal-synchronisation"
    "network-mux"
    "non-integral"
    "ntp-client"
    "optparse-applicative-fork"
    "orphans-deriving-via"
    "ouroboros-consensus"
    "ouroboros-consensus-byron"
    "ouroboros-consensus-byron-test"
    "ouroboros-consensus-byronspec"
    "ouroboros-consensus-cardano"
    "ouroboros-consensus-cardano-test"
    "ouroboros-consensus-cardano-tools"
    "ouroboros-consensus-diffusion"
    "ouroboros-consensus-mock"
    "ouroboros-consensus-mock-test"
    "ouroboros-consensus-protocol"
    "ouroboros-consensus-shelley"
    "ouroboros-consensus-shelley-test"
    "ouroboros-consensus-test"
    "ouroboros-consensus-tutorials"
    "ouroboros-network"
    "ouroboros-network-api"
    "ouroboros-network-framework"
    "ouroboros-network-mock"
    "ouroboros-network-protocols"
    "ouroboros-network-testing"
    "plutus-accumulator"
    "plutus-core"
    "plutus-ghc-stub"
    "plutus-ledger"
    "plutus-ledger-api"
    "plutus-metatheory"
    "plutus-preprocessor"
    "plutus-script-utils"
    "plutus-scripts-bench"
    "plutus-tx"
    "plutus-tx-plugin"
    "quickcheck-contractmodel"
    "quickcheck-monoids"
    "quickcheck-threatmodel"
    "scls-cardano"
    "scls-cbor"
    "scls-core"
    "scls-format"
    "set-algebra"
    "simple-semigroupoids"
    "small-steps"
    "small-steps-test"
    "sop-extras"
    "strict-sop-core"
    "trace-dispatcher"
    "trace-forward"
    "trace-resources"
    "tracer-transformers"
    "tx-generator"
    "typed-protocols-cborg"
    "typed-protocols-examples"
    "typed-protocols-stateful"
    "typed-protocols-stateful-cborg"
    "vector-map"
)

if [[ -z "${HACKAGE_TOKEN:-}" ]]; then
    echo "Error: HACKAGE_TOKEN environment variable is not set."
    exit 1
fi

TOTAL=${#PACKAGES[@]}
SUCCESS=0
FAILED=()

for i in "${!PACKAGES[@]}"; do
    pkg="${PACKAGES[$i]}"
    echo "[$((i + 1))/$TOTAL] Processing: $pkg"
    (
        cd "$pkg"
        cabal sdist
        cabal upload "dist-newstyle/sdist/${pkg}-0.0.0.0.tar.gz" --token "${HACKAGE_TOKEN}"
        curl -X PUT \
             -H "Authorization: X-ApiKey ${HACKAGE_TOKEN}" \
             "https://hackage.haskell.org/package/${pkg}/maintainers/user/IOHK"
    ) && SUCCESS=$((SUCCESS + 1)) || FAILED+=("$pkg")
done

echo ""
echo "Done: $SUCCESS/$TOTAL succeeded."

if [ ${#FAILED[@]} -gt 0 ]; then
    echo "Failed packages:"
    for pkg in "${FAILED[@]}"; do
        echo "  - $pkg"
    done
    exit 1
fi
