timestamp = 2024-12-11T19:48:20Z
github = { repo = "IntersectMBO/cardano-base", rev = "ded795b240bc86b3e71766e4e896bb4e587af679" }
subdir = 'cardano-crypto-class'

[[revisions]]
number = 1
timestamp = 2025-10-01T14:54:46Z
