timestamp = 2023-05-08T21:39:57Z
github = { repo = "input-output-hk/typed-protocols", rev = "72348fa99253f3511eec21d9ecdb0b0a47af4468" }
subdir = 'typed-protocols-cborg'

[[revisions]]
number = 1
timestamp = 2023-11-08T10:12:10Z
