timestamp = 2023-12-12T11:34:43Z
github = { repo = "input-output-hk/cardano-base", rev = "e545ee648cb7ef9d2715286dbc38987ffc3b5e4d" }
subdir = 'strict-checked-vars'

[[revisions]]
number = 1
timestamp = 2024-02-22T11:15:34Z

[[revisions]]
number = 2
timestamp = 2024-05-21T09:43:39Z

[[revisions]]
number = 3
timestamp = 2024-05-21T10:43:27Z
