timestamp = 2024-01-26T10:34:07Z
github = { repo = "IntersectMBO/cardano-ledger", rev = "6e2d37cc0f47bd02e89b4ce9f78b59c35c958e96" }
subdir = 'libs/small-steps-test'

[[revisions]]
number = 1
timestamp = 2024-06-27T01:44:37Z
