timestamp = 2024-02-22T20:53:16Z
github = { repo = "intersectmbo/ouroboros-network", rev = "c86df0277baf00c97df1dd00b6ac413e0ee49e4d" }
subdir = 'ouroboros-network-protocols'

[[revisions]]
number = 1
timestamp = 2024-04-02T10:49:14Z
