timestamp = 2022-10-17T00:00:00Z
github = { repo = "input-output-hk/cardano-ledger", rev = "c7c63dabdb215ebdaed8b63274965966f2bf408f" }
subdir = 'libs/small-steps-test'

[[revisions]]
number = 1
timestamp = 2024-06-27T01:45:40Z
