timestamp = 2024-01-05T13:49:07Z
github = { repo = "input-output-hk/cardano-node-emulator", rev = "ad1960f47c0886110d23b9c454d41e11cddfa779" }
subdir = 'plutus-ledger'

[[revisions]]
number = 1
timestamp = 2024-02-06T15:13:44Z

[[revisions]]
number = 2
timestamp = 2025-01-22T04:18:31Z
