timestamp = 2024-03-29T00:54:16Z
github = { repo = "input-output-hk/cardano-ledger", rev = "ed6d38b0bf0a54504c781b3c274745846476ca3c" }
subdir = 'eras/byron/ledger/impl'

[[revisions]]
number = 1
timestamp = 2025-03-20T18:42:33Z

[[revisions]]
number = 2
timestamp = 2025-03-22T21:54:46Z
