timestamp = 2022-10-25T17:33:07Z
github = { repo = "input-output-hk/ouroboros-network", rev = "b6ab4ca226ba541ee89374a30824351a91285226" }
subdir = 'ouroboros-consensus-shelley'

[[revisions]]
number = 1
timestamp = 2023-03-21T14:39:40Z

[[revisions]]
number = 2
timestamp = 2023-03-21T14:40:00Z
