timestamp = 2024-03-15T16:47:06Z
github = { repo = "intersectmbo/ouroboros-network", rev = "838df5513faf6272997e583d050352cc0f7d1b48" }
subdir = 'ouroboros-network-protocols'

[[revisions]]
number = 1
timestamp = 2024-04-02T10:48:51Z

[[revisions]]
number = 2
timestamp = 2024-05-07T17:19:07Z
