timestamp = 2024-10-03T14:32:17Z
github = { repo = "input-output-hk/anti-diffs", rev = "c189c934ed8d95515f9d420c37e33f1dbc55b2a4" }
subdir = 'diff-containers'

[[revisions]]
number = 1
timestamp = 2025-04-08T10:03:51Z
