timestamp = 2024-11-27T17:49:33Z
github = { repo = "intersectmbo/plutus", rev = "0effd6caecb0664ae0bc1b9c21363a7e92c35466" }
subdir = 'plutus-core'

[[revisions]]
number = 1
timestamp = 2024-12-11T19:50:43Z

[[revisions]]
number = 3
timestamp = 2025-01-22T05:35:38Z
