timestamp = 2025-02-28T13:16:07Z
github = { repo = "IntersectMBO/cardano-api", rev = "caf5632b3ccf2e3662b4ddff47aec9f7e7bb0680" }
subdir = 'cardano-api'

[[revisions]]
number = 1
timestamp = 2025-03-04T03:28:33Z
