timestamp = 2023-02-28T09:18:41Z
github = { repo = "input-output-hk/ouroboros-network", rev = "d64a5d253b751d465c5c48799dea6b234c2a329a" }
subdir = 'ouroboros-consensus'

[[revisions]]
number = 1
timestamp = 2023-03-28T09:19:04Z
