timestamp = 2025-02-26T16:38:33Z
github = { repo = "intersectmbo/ouroboros-network", rev = "588130b5f0494a42c19da3bd44211ff7607b5831" }
subdir = 'ouroboros-network-protocols'

[[revisions]]
number = 1
timestamp = 2025-04-07T00:01:49Z

[[revisions]]
number = 2
timestamp = 2025-06-20T02:35:13Z
