timestamp = 2024-01-26T10:34:07Z
github = { repo = "IntersectMBO/cardano-ledger", rev = "6e2d37cc0f47bd02e89b4ce9f78b59c35c958e96" }
subdir = 'eras/shelley/impl'

[[revisions]]
number = 1
timestamp = 2024-02-15T03:44:02Z
