timestamp = 2023-04-26T17:24:56Z
github = { repo = "input-output-hk/cardano-ledger", rev = "55a58ad476a978a24d56e8ce28b5f4bbaa159169" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2024-01-25T14:10:44Z

[[revisions]]
number = 2
timestamp = 2024-12-12T00:23:01Z
