timestamp = 2024-10-09T21:29:38Z
github = { repo = "input-output-hk/cardano-ledger", rev = "0ba8e73c41847142e0bed09e09a8aa166fc10384" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2024-12-11T19:55:16Z
