timestamp = 2022-11-23T18:31:59Z
github = { repo = "input-output-hk/ouroboros-network", rev = "926d785efb6686ee46356cf6304c688a56e1493d" }
subdir = 'ouroboros-consensus'

[[revisions]]
number = 1
timestamp = 2023-03-24T17:48:01Z
