timestamp = 2023-06-23T14:07:51Z
github = { repo = "input-output-hk/ouroboros-consensus", rev = "f40712ff376b8ee65d1d3f14f285c008ea22a634" }
subdir = 'ouroboros-consensus'

[[revisions]]
number = 1
timestamp = 2023-08-01T13:04:52Z
