timestamp = 2025-05-14T06:57:17Z
github = { repo = "intersectmbo/ouroboros-network", rev = "1eafe7bc742da1709fc98c62c48c519bbce503c0" }
subdir = 'cardano-ping'

[[revisions]]
number = 1
timestamp = 2025-06-22T22:27:17Z
