timestamp = 2023-04-29T17:52:58Z
github = { repo = "input-output-hk/ouroboros-consensus", rev = "e19a58d078b882e5180d9ef591a1f4e9a1987fe0" }
subdir = 'ouroboros-consensus-cardano'

[[revisions]]
number = 1
timestamp = 2023-05-11T21:46:07Z
