timestamp = 2023-02-28T09:19:57Z
github = { repo = "input-output-hk/ouroboros-network", rev = "d64a5d253b751d465c5c48799dea6b234c2a329a" }
subdir = 'ouroboros-consensus-diffusion'

[[revisions]]
number = 1
timestamp = 2023-04-13T17:16:53Z
