timestamp = 2025-01-08T16:35:32Z
github = { repo = "IntersectMBO/ouroboros-consensus", rev = "e924f61d1fe63d25e9ecd8499b705aff4d553209" }
subdir = 'ouroboros-consensus-protocol'

[[revisions]]
number = 1
timestamp = 2025-03-03T00:48:44Z
