timestamp = 2024-05-10T03:50:29Z
github = { repo = "IntersectMBO/cardano-ledger", rev = "15afd0483" }
subdir = 'libs/cardano-ledger-binary'

[[revisions]]
number = 1
timestamp = 2024-12-11T19:55:06Z

[[revisions]]
number = 2
timestamp = 2025-09-10T20:25:21Z
