timestamp = 2023-04-26T17:24:56Z
github = { repo = "input-output-hk/cardano-ledger", rev = "55a58ad476a978a24d56e8ce28b5f4bbaa159169" }
subdir = 'eras/shelley/impl'

[[revisions]]
number = 1
timestamp = 2023-05-10T20:07:14Z

[[revisions]]
number = 2
timestamp = 2024-02-15T15:59:55Z
