timestamp = 2024-03-21T15:31:54Z
github = { repo = "input-output-hk/ouroboros-consensus", rev = "1ef14112417a06e8e3c56a454b6c8dff9453f887" }
subdir = 'ouroboros-consensus-cardano'

[[revisions]]
number = 1
timestamp = 2024-03-28T23:05:39Z

[[revisions]]
number = 2
timestamp = 2024-04-08T09:22:59Z
