timestamp = 2023-08-04T14:05:48Z
github = { repo = "input-output-hk/cardano-base", rev = "f54cdd877c6e03bab3950f6eaa74a80881b4dcc8" }
subdir = 'strict-checked-vars'

[[revisions]]
number = 1
timestamp = 2023-11-08T10:06:26Z
