timestamp = 2022-11-17T04:56:26Z
github = { repo = "input-output-hk/cardano-node", rev = "ebc7be471b30e5931b35f9bbc236d21c375b91bb" }
subdir = 'trace-forward'
force-version = true

[[revisions]]
number = 1
timestamp = 2023-05-09T17:51:37Z
