timestamp = 2024-09-02T23:14:45Z
github = { repo = "IntersectMBO/ouroboros-consensus", rev = "3da919ffc0ef0105bc51f6bbd8dd12e8dd6990c6" }
subdir = 'sop-extras'

[[revisions]]
number = 1
timestamp = 2025-03-03T00:41:58Z
