timestamp = 2024-01-23T08:57:43Z
github = { repo = "intersectmbo/ouroboros-network", rev = "5618742c1e15ed1256fc62794eec7560040d8c0a" }
subdir = 'ouroboros-network-mock'

[[revisions]]
number = 1
timestamp = 2024-07-24T04:29:44Z
