timestamp = 2023-04-11T21:04:18Z
github = { repo = "input-output-hk/cardano-ledger", rev = "36cae5287cf6b83e714782dd6a8140df882b55de" }
subdir = 'eras/shelley/impl'

[[revisions]]
number = 1
timestamp = 2023-05-11T21:33:43Z

[[revisions]]
number = 2
timestamp = 2024-02-15T15:59:55Z
