timestamp = 2023-08-17T16:07:17Z
github = { repo = "input-output-hk/cardano-ledger", rev = "bbdfc3fdb6487653f23385c3df1c9c575bf567cf" }
subdir = 'eras/shelley/impl'

[[revisions]]
number = 1
timestamp = 2024-02-15T15:59:55Z
