timestamp = 2024-04-05T13:36:27Z
github = { repo = "jasagredo/latex-svg", rev = "c52c9905cb043ddb430c93b41ce431a7506a300d" }
subdir = 'latex-svg-image'
force-version = true

[[revisions]]
number = 1
timestamp = 2024-07-24T06:25:44Z

[[revisions]]
number = 2
timestamp = 2024-07-25T13:19:14Z
