timestamp = 2023-02-24T06:30:00Z
github = { repo = "input-output-hk/quickcheck-contractmodel", rev = "071628000ad391ba6849b4d8407b5375228d235d" }
subdir = 'quickcheck-contractmodel'

[[revisions]]
number = 1
timestamp = 2023-03-21T14:40:22Z
