timestamp = 2022-10-17T00:00:00Z
github = { repo = "input-output-hk/ouroboros-network", rev = "cb9eba406ceb2df338d8384b35c8addfe2067201" }
subdir = 'ouroboros-consensus-byron'

[[revisions]]
number = 1
timestamp = 2023-03-21T14:27:41Z
