timestamp = 2024-05-10T03:50:29Z
github = { repo = "IntersectMBO/cardano-ledger", rev = "15afd0483" }
subdir = 'libs/cardano-ledger-core'

[[revisions]]
number = 1
timestamp = 2024-12-12T00:23:01Z

[[revisions]]
number = 2
timestamp = 2025-05-13T19:30:20Z
