timestamp = 2022-11-11T00:24:50Z
github = { repo = "input-output-hk/cardano-ledger", rev = "2fac95ef338ff9622543d08fe16d0fa6716d0019" }
subdir = 'eras/byron/chain/executable-spec'

[[revisions]]
number = 1
timestamp = 2023-03-21T14:36:24Z
