timestamp = 2025-01-02T14:22:01Z
github = { repo = "intersectmbo/ouroboros-network", rev = "515767407e4a5a240e61e014c8e6d107b4fbceb9" }
subdir = 'ouroboros-network-protocols'

[[revisions]]
number = 1
timestamp = 2025-02-28T01:17:31Z
