timestamp = 2023-07-06T12:33:34Z
github = { repo = "input-output-hk/ouroboros-consensus", rev = "c50490f52ef8c8093b92a9a0f0a14d8c3e5eaf12" }
subdir = 'ouroboros-consensus-cardano'

[[revisions]]
number = 1
timestamp = 2023-07-07T12:30:00Z

[[revisions]]
number = 2
timestamp = 2023-07-07T22:31:32Z
