timestamp = 2023-02-13T11:33:09Z
github = { repo = "input-output-hk/ouroboros-network", rev = "a251fc8f8f452be2804c89ea8ea6f425ccab5dd6" }
subdir = 'ouroboros-consensus-cardano'

[[revisions]]
number = 1
timestamp = 2023-03-21T14:24:44Z
