timestamp = 2023-08-15T15:38:21Z
github = { repo = "input-output-hk/cardano-api", rev = "c5fe6d51cdd6ebaca3d012e9a96d747dc7052f4d" }
subdir = 'cardano-api'

[[revisions]]
number = 1
timestamp = 2023-08-17T18:13:21Z
