timestamp = 2023-02-21T23:26:04Z
github = { repo = "input-output-hk/cardano-base", rev = "7e64caa79e0f751f1333ccbce4a64cb48752ae69" }
subdir = 'cardano-crypto-tests'

[[revisions]]
number = 1
timestamp = 2025-01-29T20:54:25Z
