timestamp = 2026-09-04T06:57:08Z
github = { repo = "IntersectMBO/cardano-api", rev = "a1cf3a57df979436c4d6c11874ec328f2ff9b3be" }
subdir = 'cardano-api'

[[revisions]]
number = 1
timestamp = 2026-09-23T15:51:40Z

[[revisions]]
number = 2
timestamp = 2026-09-23T18:49:58Z
