timestamp = 2022-11-10T17:31:44Z
github = { repo = "input-output-hk/cardano-node", rev = "ebc7be471b30e5931b35f9bbc236d21c375b91bb" }
subdir = 'cardano-api'

[[revisions]]
number = 1
timestamp = 2023-03-21T14:29:22Z
