timestamp = 2022-08-31T08:36:42Z
url = 'https://github.com/input-output-hk/plutus/tarball/f680ac6979e069fcc013e4389ee607ff5fa6672f'
subdir = 'plutus-core'

[[revisions]]
  number = 1
  timestamp = 2022-09-07T11:54:26Z

[[revisions]]
  number = 2
  timestamp = 2022-09-07T12:30:34Z
