timestamp = 2024-10-11T20:28:21Z
github = { repo = "IntersectMBO/cardano-ledger", rev = "0ba8e73c41847142e0bed09e09a8aa166fc10384" }
subdir = 'eras/byron/ledger/impl'

[[revisions]]
number = 1
timestamp = 2024-10-11T20:35:12Z
