cabal-version: 3.8
name: cardano-rpc
version: 11.2.0.0
synopsis: A gRPC server and client for interacting with the Cardano node
description:
  A Haskell library providing a gRPC-based RPC interface for the Cardano node,
  implementing the UTxO RPC protocol for chain querying and transaction
  submission.

category:
  Blockchain,
  Cardano,
  GRPC,
  Network,
  RPC,

copyright: 2019-2023 Input Output Global Inc (IOG), 2023-2026 Intersect.
author: IOHK
maintainer: operations@iohk.io
license: Apache-2.0
license-files:
  LICENSE
  NOTICE

build-type: Simple
extra-doc-files:
  CHANGELOG.md
  README.md

common project-config
  default-language: Haskell2010
  default-extensions:
    ImportQualifiedPost
    OverloadedStrings

  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wno-unticked-promoted-constructors
    -Wpartial-fields
    -Wredundant-constraints
    -Wunused-packages

library
  import: project-config
  hs-source-dirs: src
  exposed-modules:
    Cardano.Rpc.Client
    Cardano.Rpc.Proto.Api.Node
    Cardano.Rpc.Proto.Api.UtxoRpc.Query
    Cardano.Rpc.Proto.Api.UtxoRpc.Submit
    Cardano.Rpc.Proto.Api.UtxoRpc.Sync
    Cardano.Rpc.Server
    Cardano.Rpc.Server.Config
    Cardano.Rpc.Server.Internal.Env
    Cardano.Rpc.Server.Internal.Error
    Cardano.Rpc.Server.Internal.Monad
    Cardano.Rpc.Server.Internal.Node
    Cardano.Rpc.Server.Internal.TimedCache
    Cardano.Rpc.Server.Internal.Tracing
    Cardano.Rpc.Server.Internal.UtxoRpc.Eval
    Cardano.Rpc.Server.Internal.UtxoRpc.Predicate
    Cardano.Rpc.Server.Internal.UtxoRpc.Query
    Cardano.Rpc.Server.Internal.UtxoRpc.Submit
    Cardano.Rpc.Server.Internal.UtxoRpc.Sync
    Cardano.Rpc.Server.Internal.UtxoRpc.Type
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.BigInt
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.Block
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.Byron
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.Certificate
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.ChainPoint
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.Genesis
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.Governance
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.PlutusData
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.ProtocolParameters
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.Rational
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.Script
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.Tx
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.TxEval
    Cardano.Rpc.Server.Internal.UtxoRpc.Type.TxOutput
    Cardano.Rpc.Server.NodeKernelAccess
    Cardano.Rpc.Server.NodeKernelAccess.Type

  other-modules:
    Cardano.Rpc.Server.Internal.Orphans
    Paths_cardano_rpc

  autogen-modules:
    Paths_cardano_rpc

  build-depends:
    aeson,
    base,
    base16-bytestring,
    bytestring,
    cardano-api >=11.5,
    cardano-binary,
    cardano-crypto,
    cardano-crypto-class,
    cardano-crypto-wrapper,
    cardano-ledger-allegra,
    cardano-ledger-alonzo,
    cardano-ledger-api,
    cardano-ledger-binary,
    cardano-ledger-byron,
    cardano-ledger-conway,
    cardano-ledger-core >=1.19,
    cardano-ledger-dijkstra,
    cardano-ledger-shelley,
    cardano-rpc:gen,
    containers,
    contra-tracer,
    data-default,
    errors,
    filepath,
    formatting,
    fs-api ^>=0.4,
    generic-data,
    grapesy,
    grpc-spec,
    memory,
    mempack,
    microlens,
    proto-lens >=0.7.1.7,
    proto-lens-protobuf-types,
    random,
    rio,
    strict-sop-core,
    text,
    time,

-- this should be replaced by utxorpc package from hackage
-- ideally we should upstream whatever is implemented in Proto.Cardano.Rpc.Node
-- into utxorpc
library gen
  import: project-config
  hs-source-dirs: gen
  exposed-modules:
    Proto.Cardano.Rpc.Node
    Proto.Cardano.Rpc.Node_Fields
    Proto.Utxorpc.V1beta.Cardano.Cardano
    Proto.Utxorpc.V1beta.Cardano.Cardano_Fields
    Proto.Utxorpc.V1beta.Query.Query
    Proto.Utxorpc.V1beta.Query.Query_Fields
    Proto.Utxorpc.V1beta.Submit.Submit
    Proto.Utxorpc.V1beta.Submit.Submit_Fields
    Proto.Utxorpc.V1beta.Sync.Sync
    Proto.Utxorpc.V1beta.Sync.Sync_Fields

  build-depends:
    proto-lens-protobuf-types,
    proto-lens-runtime,

test-suite cardano-rpc-test
  import: project-config
  hs-source-dirs: test/cardano-rpc-test
  main-is: cardano-rpc-test.hs
  type: exitcode-stdio-1.0
  build-depends:
    aeson,
    base,
    base16-bytestring,
    bytestring,
    cardano-api,
    cardano-api:gen,
    cardano-crypto,
    cardano-crypto-wrapper,
    cardano-crypto-wrapper:testlib,
    cardano-ledger-alonzo,
    cardano-ledger-alonzo:testlib,
    cardano-ledger-api,
    cardano-ledger-binary,
    cardano-ledger-byron,
    cardano-ledger-byron:testlib,
    cardano-ledger-conway,
    cardano-ledger-conway:testlib,
    cardano-ledger-core >=1.19,
    cardano-ledger-dijkstra,
    cardano-ledger-shelley,
    cardano-ledger-shelley:testlib,
    cardano-rpc,
    containers,
    formatting,
    grpc-spec,
    hedgehog,
    hedgehog-extras,
    hedgehog-quickcheck,
    memory,
    mtl,
    ouroboros-consensus:cardano,
    proto-lens,
    rio,
    scientific,
    tasty,
    tasty-hedgehog,
    text,
    time,
    zlib,

  ghc-options:
    -threaded
    -rtsopts
    "-with-rtsopts=-N -T"

  build-tool-depends: tasty-discover:tasty-discover
  other-modules:
    Test.Cardano.Rpc.ByronTx
    Test.Cardano.Rpc.Eval
    Test.Cardano.Rpc.FetchBlockTx
    Test.Cardano.Rpc.FollowTipStream
    Test.Cardano.Rpc.Genesis.Fixture
    Test.Cardano.Rpc.Genesis.Property
    Test.Cardano.Rpc.Pagination
    Test.Cardano.Rpc.Predicate
    Test.Cardano.Rpc.ProtocolParameters
    Test.Cardano.Rpc.Script
    Test.Cardano.Rpc.TxOutput
    Test.Cardano.Rpc.Type
