timestamp = 2023-04-17T12:31:04Z
github = { repo = "input-output-hk/plutus", rev = "cfccccc8596859bfaa992100b11199301eb6d2bd" }
subdir = 'plutus-core'
force-version = true

[[revisions]]
number = 1
timestamp = 2023-07-21T09:28:47Z
