timestamp = 2023-05-10T04:41:56Z
github = { repo = "input-output-hk/ouroboros-network", rev = "d1d3e4b1ce783572a643103d9799a2a8a5e7159a" }
subdir = 'ouroboros-network-protocols'

[[revisions]]
number = 1
timestamp = 2023-05-17T06:53:34Z
